### ISSUE TITLE
fdroid

### ISSUE THREAD

**Issue by ahmed-tasaly** [Five-Prayers/five-prayers-android#21]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Add the app to fdroid or create a custom fdroid repo

**_Thanks in advance_**

**Comment by DragoonFX** [comment]
I second this. Please consider adding this app on fdroid.

**Comment by HichamBI** [comment]
Hello,

Currently, am developing new features, I'll consider adding the application on f droid. By the begening of the year.

BR,

**Comment by HichamBI** [comment]
Hello @junnunkarim  @ahmed-tasaly 

I've created an F-Droid specific repo :

- Repo url:  https://raw.githubusercontent.com/Five-Prayers/fdroid-repo-stable/main/fdroid/repo
- Fingerprint: C8 E3 6E 27 BA 66 CB 81 D9 24 9C 55 C6 7A 8E 53 21 AF DB CC F8 1E EB 0D 49 5E 8E 3A 01 FE 16 93

This is the fastest way, considering that the application wont compile in F-Droid because of some copyrighted assets (calligraphy SVG) or external APIs access Tokens, that are not published with the source code.

I hope that can help.
BR,
