### ISSUE TITLE
increase the size of the text of the widget

### ISSUE THREAD

**Issue by ahmed-tasaly** [Five-Prayers/five-prayers-android#27]
السلام عليكم 

هل يمكنك تكبير خط (font) ال widget قليلا ? 
و شكرا

**Comment by HichamBI** [comment]
Salam Alaykoum.

I cannot increase text size for this widget for the moment. I'm currently supporting differents phone sizes and resolutions, and also, I'm supporting AM/PM time formats. Putting text size in 14sp instead of 13sp will make the widget ugly: 

![image](https://user-images.githubusercontent.com/8617460/174488107-3585e25e-e6e9-4265-b5e6-4cbdb2da3390.png)

Currently, I'm working on a new Widget in addition of the existing one. Text size will bigger. There is a preview:

![image](https://user-images.githubusercontent.com/8617460/174488253-a1b654f6-8934-4f36-814a-6a620eef16e6.png)

It will be available in 2.7.0 version Inchae Lah.

BR.
Hicham.

**Comment by ahmed-tasaly** [comment]
> Salam Alaykoum.
> 
> I cannot increase text size for this widget for the moment. I'm currently supporting differents phone sizes and resolutions, and also, I'm supporting AM/PM time formats. Putting text size in 14sp instead of 13sp will make the widget ugly:
> 
> ![image](https://user-images.githubusercontent.com/8617460/174488107-3585e25e-e6e9-4265-b5e6-4cbdb2da3390.png)
> 
> Currently, I'm working on a new Widget in addition of the existing one. Text size will bigger. There is a preview:
> 
> ![image](https://user-images.githubusercontent.com/8617460/174488253-a1b654f6-8934-4f36-814a-6a620eef16e6.png)
> 
> It will be available in 2.7.0 version Inchae Lah.
> 
> BR. Hicham.

thank you 🤍
جزاك الله خيرا
