### ISSUE TITLE
Add Tafsir feature in quran section

### ISSUE THREAD

**Issue by Qube01** [Five-Prayers/five-prayers-android#38]
**Is your feature request related to a problem? Please describe.**
Yes, when I read the Quran I would like to check tafsir to understand what I'm reading, which is not in this app.

**Describe the solution you'd like**
Clicking on a verse displays it's tafsir (in Arabic or possibly in the language of the app or user)

**Additional context**
IDK if it's useful for you but here is a source code of an app with the same purpose that is probably dead, maybe you can benefit from it :
https://github.com/mirfatif/NoorUlHuda

**Comment by HichamBI** [comment]
Hello/Salam Alaykoum,

Thank you for your support and for opening this issue.

Honestly I don't think this feature is relevant for this project. Since there is another open-source project whose goal is to provide a very good user experience for The Quran. This kind of features requires a lot of effort and it would just be redundant. The Quran section in Five Prayers Android is for who want to read Quran. For users who want to learn Quran with explanations, Listening ... I recommend to consider this open-source project [Quran Android](https://github.com/quran/quran_android).

May be, it can be revelent to add Quran audio files for who want to listen, but I will not go beyond of this.

BR,

**Comment by Qube01** [comment]
I see, I thought that would make the app more complete but that's fine.
